version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts  # Utilise la version LTS stable de Jenkins
    container_name: "jenkins"
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /srv/data/jenkins_data:/var/jenkins_home  # Correctement lié au dossier de Jenkins
      - /srv/data/jenkins:/var/jenkins_config

volumes:
  jenkins_data:
    driver: local
